version: "2"

services:
  db: 
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  prometheus:
    image: prom/prometheus
    ports: 
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports: 
      - "3000:3000"

